version: '3.8'

services:
  earthquake-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: earthquake-api
    command: python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres-db
    networks:
      - earthquake-api

  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure
    networks:
      - earthquake-api

networks:
  earthquake-api:
    driver: bridge

volumes:
  postgres_data: