# Generated by Django 4.2.7 on 2023-11-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resources",
            "0003_alter_earthquake_location_name_alter_earthquake_mmi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="earthquake",
            name="mmi",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seismicintensity",
            name="mmi",
            field=models.IntegerField(default=0),
        ),
    ]
