# Generated by Django 4.2.7 on 2023-11-13 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_alter_earthquake_mmi_alter_seismicintensity_mmi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="earthquake",
            name="seismic",
        ),
        migrations.AlterField(
            model_name="earthquake",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="earthquake",
            name="mmi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.seismicintensity",
            ),
        ),
        migrations.AlterField(
            model_name="seismicintensity",
            name="mmi",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="seismicintensity",
            name="scale_level",
            field=models.CharField(max_length=50),
        ),
    ]
