# Generated by Django 4.2.7 on 2023-11-13 10:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0006_alter_earthquake_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earthquake",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
