# Generated by Django 4.2.7 on 2023-11-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0007_alter_earthquake_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="seismicintensity",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
