# Generated by Django 4.2.7 on 2023-11-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_seismicintensity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seismicintensity',
            name='name',
        ),
    ]
